[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[build]
    publish = "build"
    command = "bun run build"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
